### ISSUE TITLE
Latest 5e-convert.exe gives error when indexing.

### ISSUE THREAD

**Issue by Bugmaniac71** [ebullient/json5e-convert-cli#72]
g:\OneDrive\Documents\ObsidianScripts\5e-convert>5e-convert.exe --index -o dm 5etools-mirror-1.github.io/data
ÔÅ▒  Reading g:\OneDrive\Documents\ObsidianScripts\5e-convert\5etools-mirror-1.github.io\data
Ô£à finished reading 5etools data.
java.lang.IllegalArgumentException: argument "in" is null
        at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4829)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3055)
        at dev.ebullient.json5e.io.Json5eTui.readResource(Json5eTui.java:254)
        at dev.ebullient.json5e.io.Json5eTui_ClientProxy.readResource(Unknown Source)
        at dev.ebullient.json5e.tools5e.JsonIndex.prepare(JsonIndex.java:221)
        at dev.ebullient.json5e.Json5eConvertCli.call(Json5eConvertCli.java:163)
        at dev.ebullient.json5e.Json5eConvertCli.call(Json5eConvertCli.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at dev.ebullient.json5e.Json5eConvertCli.executionStrategy(Json5eConvertCli.java:191)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.ebullient.json5e.Json5eConvertCli.run(Json5eConvertCli.java:211)
        at dev.ebullient.json5e.Json5eConvertCli_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:131)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:43)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

**Comment by ebullient** [comment]
thanks for the heads up!

**Comment by Bugmaniac71** [comment]
Confirmed all good now thank you!
